services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: nestjs_auth_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - nestjs_auth_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
   
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: nestjs_auth_app
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - nestjs_auth_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: nestjs_auth_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - nestjs_auth_network

  redis:
    image: redis:7
    container_name: nestjs_auth_redis
    ports:
        - "${REDIS_PORT:-6379}:6379"  
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - nestjs_auth_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"${REDIS_PASSWORD}\" ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: nestjs_auth_redis_insight
    restart: unless-stopped
    ports:
      - "8001:5540"
    environment:
      - RITRUSTEDORIGINS=http://localhost:8001
    volumes:
      - redis_insight_data:/db
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - nestjs_auth_network



  node_exporter:
    image: prom/node-exporter:latest
    container_name: nestjs_auth_node_exporter
    command:
      - '--path.rootfs=/host'
    pid: "host"
    volumes:
      - /:/host:ro
    restart: always
    ports:
      - "9100:9100"
    networks:
      - nestjs_auth_network



  prometheus:
    image: prom/prometheus:latest
    container_name: nestjs_auth_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - node_exporter
    networks:
      - nestjs_auth_network

  grafana:
    image: grafana/grafana:latest
    container_name: nestjs_auth_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - nestjs_auth_network

networks:
  nestjs_auth_network:
    driver: bridge

volumes:
  redis_insight_data:
  postgres_data: